# Generated by Django 2.2.11 on 2022-03-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureAirport', models.CharField(max_length=500)),
                ('DepartureAirportICAOCode', models.CharField(max_length=50)),
                ('ArrivalAirport', models.CharField(max_length=500)),
                ('ArrivalAirportICAOCode', models.CharField(max_length=50)),
            ],
        ),
    ]
