# Generated by Django 2.2.11 on 2022-03-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airlineroute',
            unique_together={('DepartureAirportICAOCode', 'ArrivalAirportICAOCode')},
        ),
    ]
