# Generated by Django 2.2.11 on 2022-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlineaircraft',
            name='aircraftICAOcode',
            field=models.CharField(max_length=50),
        ),
    ]
