# Generated by Django 2.2.11 on 2022-09-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20220903_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineroute',
            name='airline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airline.Airline'),
        ),
    ]
