# Generated by Django 2.2.11 on 2022-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_airlineroute_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='Name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
