# Generated by Django 2.2.11 on 2023-01-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_auto_20221210_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAborted', models.BooleanField()),
                ('flightDurationSeconds', models.FloatField()),
                ('initialTakeOffMassKg', models.FloatField()),
                ('finalMassKg', models.FloatField()),
                ('airline', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airline.Airline')),
                ('airlineAircraft', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airline.AirlineAircraft')),
                ('airlineRoute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airline.AirlineRoute')),
            ],
        ),
    ]
