# Generated by Django 2.2.11 on 2022-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_airlineroutewaypoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('MinLongitudeDegrees', models.FloatField()),
                ('MinLatitudeDegrees', models.FloatField()),
                ('MaxLongitudeDegrees', models.FloatField()),
                ('MaxLatitudeDegrees', models.FloatField()),
            ],
        ),
    ]
