# Generated by Django 2.2.11 on 2023-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_airlinecosts_finallengthmeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinecosts',
            name='adepRunway',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='airlinecosts',
            name='adesRunway',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='airlinecosts',
            name='targetCruiseLevelFeet',
            field=models.FloatField(default=0.0),
        ),
    ]
