# Generated by Django 2.2.11 on 2023-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_auto_20230429_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineaircraft',
            name='turnAroundTimesMinutes',
            field=models.FloatField(default=0),
        ),
    ]
