# Generated by Django 3.2 on 2023-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_airlineaircraft_turnaroundtimesminutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userIp', models.CharField(default=None, max_length=150, primary_key=True, serialize=False)),
                ('connexions', models.IntegerField(default=0)),
            ],
        ),
    ]
