# Generated by Django 3.2 on 2023-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstCnxDateTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='lastCnxDateTime',
            field=models.DateTimeField(default=None),
        ),
    ]
