# Generated by Django 3.2 on 2024-01-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0011_auto_20230710_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinecosts',
            name='reducedClimbPowerCoeff',
            field=models.FloatField(default=0.0),
        ),
    ]
